In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [93]:
df_2011 = pd.read_stata("./2011_WAVE_1/psu.dta")

In [94]:
df_2011

    communityID          province        city urban_nbs areatype
0       0940041              ±±¾©        ±±¾©     Urban      111
1       0940042              ±±¾©        ±±¾©     Urban      111
2       0940043              ±±¾©        ±±¾©     Urban      111
3       1940373              Ìì½ò        Ìì½ò     Urban      112
4       1940371              Ìì½ò        Ìì½ò     Urban      112
..          ...               ...         ...       ...      ...
445     0467461            Çàº£Ê¡    º£¶«µØÇø     Rural      220
446     0467463            Çàº£Ê¡    º£¶«µØÇø     Rural      220
447     0896762  ÐÂ½®Î¬Îá¶û×ÔÖÎÇø  °¢¿ËËÕµØÇø     Urban      121
448     0896763  ÐÂ½®Î¬Îá¶û×ÔÖÎÇø  °¢¿ËËÕµØÇø     Urban      121
449     0896761  ÐÂ½®Î¬Îá¶û×ÔÖÎÇø  °¢¿ËËÕµØÇø     Rural      220

[450 rows x 5 columns]

In [91]:
# pd.set_option('display.max_rows', None)
pd.reset_option('display.max_rows')
urban_2011 = df_2011[df_2011.urban_nbs == "Urban"]
urban_2011

    communityID          province        city urban_nbs areatype
0       0940041              ±±¾©        ±±¾©     Urban      111
1       0940042              ±±¾©        ±±¾©     Urban      111
2       0940043              ±±¾©        ±±¾©     Urban      111
3       1940373              Ìì½ò        Ìì½ò     Urban      112
4       1940371              Ìì½ò        Ìì½ò     Urban      112
..          ...               ...         ...       ...      ...
434     1340043            ¸ÊËàÊ¡      À¼ÖÝÊÐ     Urban      111
435     1382022            ¸ÊËàÊ¡      ÕÅÒ´ÊÐ     Urban      121
441     1349022            ¸ÊËàÊ¡      ¶¨Î÷ÊÐ     Urban      121
447     0896762  ÐÂ½®Î¬Îá¶û×ÔÖÎÇø  °¢¿ËËÕµØÇø     Urban      121
448     0896763  ÐÂ½®Î¬Îá¶û×ÔÖÎÇø  °¢¿ËËÕµØÇø     Urban      121

[213 rows x 5 columns]

In [169]:
urban_2011[urban_2011["province"] == "¸ÊËàÊ¡"]

    communityID province    city urban_nbs areatype
432     1340041   ¸ÊËàÊ¡  À¼ÖÝÊÐ     Urban      112
433     1340042   ¸ÊËàÊ¡  À¼ÖÝÊÐ     Urban      111
434     1340043   ¸ÊËàÊ¡  À¼ÖÝÊÐ     Urban      111
435     1382022   ¸ÊËàÊ¡  ÕÅÒ´ÊÐ     Urban      121
441     1349022   ¸ÊËàÊ¡  ¶¨Î÷ÊÐ     Urban      121

In [100]:
urban_2011[urban_2011["province"] == "±±¾©"]

  communityID province  city urban_nbs areatype
0     0940041     ±±¾©  ±±¾©     Urban      111
1     0940042     ±±¾©  ±±¾©     Urban      111
2     0940043     ±±¾©  ±±¾©     Urban      111

In [166]:
urban_2011[urban_2011["province"] == "ÔÆÄÏÊ¡"]

    communityID province    city urban_nbs areatype
391     0140511   ÔÆÄÏÊ¡  À¥Ã÷ÊÐ     Urban      121
392     0140512   ÔÆÄÏÊ¡  À¥Ã÷ÊÐ     Urban      123
393     0140313   ÔÆÄÏÊ¡  À¥Ã÷ÊÐ     Urban      111
394     0140311   ÔÆÄÏÊ¡  À¥Ã÷ÊÐ     Urban      111
396     0101042   ÔÆÄÏÊ¡  ±£É½ÊÐ     Urban      111
399     0104462   ÔÆÄÏÊ¡  ÕÑÍ¨ÊÐ     Urban      122
401     0104461   ÔÆÄÏÊ¡  ÕÑÍ¨ÊÐ     Urban      121
405     0182062   ÔÆÄÏÊ¡  Àö½­ÊÐ     Urban      122
408     0146432   ÔÆÄÏÊ¡  ÁÙ²×ÊÐ     Urban      121
409     0146431   ÔÆÄÏÊ¡  ÁÙ²×ÊÐ     Urban      122

1. Lets focus on ±±¾© province now.

In [101]:
df_2011_health = pd.read_stata("./2011_WAVE_1/health_status_and_functioning.dta")

In [102]:
df_2011_health

,ID,householdID,communityID,da001,da002,da003,da004,da005_1_,da005_2_,da005_3_,...,de017,de018,de019,de020,de021,de022,de023,de024,flda081_1,proxy
0,09400411301,094004113,0940041,NaN,4 Poor,2 No,2 No,2 No,2 No,2 No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75Ëê,0 No
1,09400411302,094004113,0940041,NaN,2 Good,2 No,2 No,2 No,2 No,2 No,...,3 Moderate,3 Moderate,3 Moderate,4 Severe,5 Extreme,NaN,NaN,NaN,75Ëê,0 No
2,09400410301,094004103,0940041,NaN,3 Fair,1 Yes,2 No,2 No,2 No,2 No,...,NaN,NaN,2 Mild,4 Severe,4 Severe,NaN,NaN,NaN,90Ëê,0 No
3,09400411102,094004111,0940041,NaN,3 Fair,2 No,2 No,2 No,2 No,2 No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75Ëê,0 No
4,09400411101,094004111,0940041,NaN,4 Poor,2 No,2 No,2 No,2 No,2 No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75Ëê,0 No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17591,29409930401,294099304,2940993,2 Very good,NaN,NaN,NaN,2 No,2 No,2 No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1 Yes
17592,29409930302,294099303,2940993,2 Very good,NaN,2 No,2 No,2 No,2 No,2 No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75Ëê,0 No
17593,29409930301,294099303,2940993,4 Fair,NaN,2 No,2 No,2 No,2 No,2 No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75Ëê,0 No
17594,29409931101,294099311,2940993,NaN,3 Fair,NaN,NaN,2 No,2 No,2 No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,1 Yes
17595,29409931102,294099311,2940993,5 Poor,NaN,2 No,2 No,2 No,2 No,2 No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75Ëê,0 No

province, city = ±±¾©, ±±¾©

In [103]:
df_2011_health_city1_ID1 =  df_2011_health[df_2011_health["communityID"] == "0940041"]
df_2011_health_city1_ID2 =  df_2011_health[df_2011_health["communityID"] == "0940042"]
df_2011_health_city1_ID3 =  df_2011_health[df_2011_health["communityID"] == "0940043"]
# df_2011_health_city1 = pd.DataFrame()
# combined_df = pd.concat([df1, df2, df3], ignore_index=True)
df_2011_health_city1 = pd.concat([df_2011_health_city1_ID1,df_2011_health_city1_ID2, df_2011_health_city1_ID3 ], ignore_index=True)

In [104]:
df_2011_health_city1.shape

(93, 591)

In [105]:
df_2011_health_city1.isna().sum()

ID              0
householdID     0
communityID     0
da001          42
da002          51
               ..
de022          84
de023          84
de024          84
flda081_1       0
proxy           0
Length: 591, dtype: int64

In [107]:
#slef comments on health
df_2011_health_city1.da002

0     4 Poor
1     2 Good
2     3 Fair
3     3 Fair
4     4 Poor
       ...
88       NaN
89    3 Fair
90       NaN
91       NaN
92       NaN
Name: da002, Length: 93, dtype: category
Categories (5, object): ['1 Very good' < '2 Good' < '3 Fair' < '4 Poor' < '5 Very poor']

In [109]:
# hepertension
df_2011_health_city1.da007_1_.isna().sum()

0

In [110]:
# Diabetes
df_2011_health_city1.da007_3_.isna().sum()

0

In [115]:
# Memory related disease
df_2011_health_city1.da007_12_.isna().sum()

0

In [ ]:
# Asthma
df_2011_health_city1.da007_14_.isna().sum()

In [116]:
# Rheumatism
df_2011_health_city1.da007_13_.isna().sum()

0

In [111]:
# Cancer
df_2011_health_city1.da007_4_.isna().sum()

0

In [112]:
# Chronic Lung Disease
df_2011_health_city1.da007_5_.isna().sum()

0

In [113]:
# Liver Disease
df_2011_health_city1.da007_6_.isna().sum()

0

In [114]:
# Stomach or digestive Disease
df_2011_health_city1.da007_10_.isna().sum()

0

Background

In [161]:
df_2011_backgrnd = pd.read_stata("./CHARLS2013_WAVE2/demographic_background.dta")
df_2011_backgrnd_city1_ID1= df_2011_backgrnd[df_2011_backgrnd["communityID"] == "0940041"]
df_2011_backgrnd_city1_ID2 = df_2011_backgrnd[df_2011_backgrnd["communityID"] == "0940042"]
df_2011_backgrnd_city1_ID3 = df_2011_backgrnd[df_2011_backgrnd["communityID"] == "0940043"]
df_2011_backgrnd_city1 = pd.concat([df_2011_backgrnd_city1_ID1,df_2011_backgrnd_city1_ID2, df_2011_backgrnd_city1_ID3], ignore_index=True)
# df_2011_backgrnd_city1.shape

(88, 145)

In [164]:
pd.set_option('display.max_columns', None)

df_2011_backgrnd_city1
# ba004 === Age
# bb001 3== province
# df_2011_backgrnd.ba004.isna().sum()
# df_2011_backgrnd.shape
# pd.reset_option('display.max_columns')

,ID,householdID,communityID,xrtype,zba001,zba002_1,zba002_2,zba002_3,zbc001,zbc005,zbd001,ba000_w2_3,ba001,ba001_w2_1,ba002_1,ba002_2,ba002_3,ba003,ba004,ba005,ba006_w2_1,ba007_w2_1,ba007_w2_1_1,bb000_w2_1,bb000_w2_1_1,bb000_w2_2,bb000_w2_2_1,bb001,bb002,bb003,bb004,bb005,bb006,bb007,bb008_1,bb008_2,bb009,bb010_1,bb010_2,bb011,bb012,bb012_1,bb013_w2_1,bb013_w2_1_1,bc001,bc001_w2_1,bc001_w2_2,bc001_w2_2_1,bc001_w2_3,bc001_w2_3_1,bc001_w2_4,bc002,bc003_1,bc003_2,bc004_1,bc004_2,bc005_w2_1,bc005,bc005_2,bc005_w2_2,bc005_w2_2_1,bc005_w2_3,bc006_1,bc006_2,bc007,bc008,bc009,bc010,bc011,bc011_2,bc012,bc012_1,bc013,bc013_2,bc015,bc015_1,bc016_1,bc016_2,bc017,bc017_1,bc018_1,bc018_2,bd001_w2_1,bd001_w2_2,bd001_w2_3,bd001_w2_4,bd001,bd002,bd002_w2_1,bd003,bd004,bd005,bd006,bd007_w2_1s1,bd007_w2_1s2,bd007_w2_1s3,bd007_w2_1s4,bd007_w2_1s5,bd007_w2_1s6,bd007_w2_1s7,bd007_w2_1s8,bd007s1,bd007s2,bd007s3,bd007s4,bd007s5,bd007s6,bd007s7,bd007s8,bd008,bd008_w2_1,bd009,bd009_w2_1,bd010,bd011,be001,be003,be003_w2_1,be004_1,be004_2,be005,be009_1,be009_2,bf001,bf002_1,bf002_2,bf003,bf004,bf005_1,bf005_2,bf006_1,bf006_2,bf006_w2_1,bf006_w2_1_1,bf006_w2_2,bf006_w2_2_1,bf006_w2_2_2,bf006_w2_3,bf006_w2_4,bf007_1,bf007_2,bf008,bf009,bf010,versionID
0,094004101002,0940041010,0940041,2 REIW Followup Interview,4 Rabbit,1951.0,12.0,17.0,2 Non-agricultural Hukou,2 Birthplace,5 Middle school,2 female,NaN,1 Yes,NaN,NaN,NaN,NaN,NaN,1 Go Home Almost Every Day,2 No,1 Han,,1 The Same Address,,1 Family housing,,2 Another Village/Neighborhood in Permanent Ad...,1 Rural Village,NaN,NaN,2003.0,NaN,NaN,NaN,NaN,2 No,NaN,NaN,NaN,NaN,,NaN,,2 Non-agricultural Hukou,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,2 No,1 Permanent Address,,"6 others, pls specify",ÎÞ²»Ò»Ñù,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,,NaN,NaN,NaN,,NaN,NaN,1 Yes,2 No,NaN,12 No Change,NaN,NaN,NaN,NaN,NaN,NaN,14.0,1 None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 Widowed,NaN,0.0,NaN,NaN,NaN,NaN,NaN,8 Goat,1943.0,12.0,1 Solar calendar,9 Four Year College / Bachelors degree,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,2011.0,9.0,1 Never,NaN,NaN,20151118
1,094004103001,0940041030,0940041,2 REIW Followup Interview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 female,11 Dog,NaN,1984.0,10.0,10.0,2 Lunar calendar,NaN,1 Go Home Almost Every Day,2 No,1 Han,,1 The Same Address,,1 Family housing,,2 Another Village/Neighborhood in Permanent Ad...,1 Rural Village,NaN,NaN,1965.0,1 Village,NaN,NaN,NaN,2 No,NaN,NaN,NaN,NaN,,NaN,,2 Non-agricultural Hukou,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,1958.0,0.0,NaN,1 Permanent Address,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,5 Middle school,NaN,NaN,0.0,NaN,16.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 Widowed,1.0,NaN,1953.0,12.0,0.0,NaN,NaN,6 Snake,1929.0,1.0,2 Lunar calendar,4 Elementary school,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,2000.0,1.0,2 A few times,NaN,NaN,20151118
2,094004104001,0940041040,0940041,2 REIW Followup Interview,2 Ox,1949.0,9.0,18.0,1 Agricultual Hukou,1 Permanent Address,5 Middle school,2 female,NaN,1 Yes,NaN,NaN,NaN,NaN,NaN,1 Go Home Almost Every Day,2 No,1 Han,,1 The Same Address,,1 Family housing,,3 Other County/City/District,1 Rural Village,2007.0,2 No,2010.0,NaN,2 No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,1 Agricultual Hukou,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,2 No,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,,NaN,NaN,NaN,,NaN,NaN,1 Yes,2 No,NaN,5 Middle School,NaN,NaN,NaN,0.0,NaN,NaN,19.0,1 None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Married with spouse present,NaN,1.0,1971.0,10.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,1 Never,NaN,NaN,20151118
3,094004104002,0940041040,0940041,2 REIW Followup Interview,1 Rat,1948.0,9.0,15.0,2 Non-agricultural Hukou,1 Permanent Address,6 High school,1 male,NaN,1 Yes,NaN,NaN,NaN,NaN,NaN,1 Go Home Almost Every Day,1 Yes,1 Han,,1 The Same Address,,1 Family housing,,3 Other County/City/District,1 Rural Village,2007.0,2 No,2010.0,NaN,2 No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,2 Non-agricultural Hukou,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,2 No,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,,NaN,NaN,NaN,,NaN,NaN,1 Yes,2 No,NaN,6 High School,NaN,NaN,NaN,0.0,NaN,NaN,21.0,1 None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Married with spouse present,NaN,1.0,1971.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,2 A few times,NaN,NaN,20151118
4,094004105001,0940041050,0940041,2 REIW Followup Interview,6 Snake,1953.0,11.0,15.0,2 Non-agricultural Hukou,2 Birthplace,4 Elementary school,2 female,NaN,1 Yes,NaN,NaN,NaN,NaN,NaN,1 Go Home Almost Every Day,2 No,1 Han,,1 The Same Address,,1 Family housing,,1 The Same As Permanent Address,2 Urban Community,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 No,NaN,NaN,NaN,NaN,,NaN,,2 Non-agricultural Hukou,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,2 No,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,,NaN,NaN,NaN,,NaN,NaN,1 Yes,2 No,NaN,12 No Change,NaN,NaN,NaN,NaN,NaN,NaN,14.0,1 None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Married with spouse present,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,1 Never,NaN,NaN,20151118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,094004310002,0940043100,0940043,2 REIW Followup Interview,9 Monkey,1932.0,6.0,16.0,2 Non-agricultural Hukou,2 Birthplace,1 No formal education illiterate,2 female,NaN,1 Yes,NaN,NaN,NaN,NaN,NaN,1 Go Home Almost Every Day,2 No,1 Han,,1 The Same Address,,1 Family housing,,2 Another Village/Neighborhood in Permanent Ad...,2 Urban Community,NaN,NaN,1994.0,NaN,NaN,NaN,NaN,2 No,NaN,NaN,NaN,NaN,,NaN,,2 Non-agricultural Hukou,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,2 No,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,,NaN,NaN,NaN,,NaN,NaN,1 Yes,2 No,NaN,1 No Formal Education (Illiterate),NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Married with spouse present,NaN,1.0,1958.0,9.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,1 Never,NaN,NaN,20151118
84,094004311001,0940043110,0940043,1 NEWIW New Interview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 female,10 Rooster,NaN,1969.0,9.0,20.0,1 Solar calendar,NaN,1 Go Home Almost Every Day,2 No,1 Han,,1 The Same Address,,1 Family housing,,3 Other County/City/District,2 Urban Community,2007.0,1 Yes,NaN,2 City/Town,2 No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,2 Non-agricultural Hukou,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,2004.0,0.0,NaN,4 Other County/City/District,,NaN,,NaN,5.0,0.0,2 No,2 No,3 Only Hukou place has changed,NaN,NaN,,NaN,,1 Birthplace,,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,8 Two/Three Year College / Associate degree,NaN,NaN,0.0,1990.0,8.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Married with spouse present,1.0,NaN,1993.0,5.0,3000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,1 Never,NaN,NaN,20151118
85,094004311002,0940043110,0940043,1 NEWIW New Interview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 male,9 Monkey,NaN,1968.0,6.0,24.0,1 Solar calendar,NaN,1 Go Home Almost Every Day,1 Yes,1 Han,,1 The Same Address,,1 Family housing,,3 Other County/City/District,2 Urban Community,2007.0,1 Yes,NaN,2 City/Town,2 No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,2 Non-agricultural Hukou,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,2004.0,0.0,NaN,4 Other County/City/District,,NaN,,NaN,8.0,2.0,2 No,2 No,3 Only Hukou place has changed,NaN,NaN,,NaN,,1 Birthplace,,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,"10 Post-graduate, Masters degree",NaN,NaN,0.0,1986.0,8.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Married with spouse present,1.0,NaN,1993.0,5.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,1 Never,NaN,NaN,20151118
86,094004312001,0940043120,0940043,1 NEWIW New Interview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20151118
87,094004312002,0940043120,0940043,1 NEWIW New Interview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 female,2 Ox,NaN,1961.0,10.0,0.0,1 Solar calendar,NaN,1 Go Home Almost Every Day,2 No,1 Han,,1 The Same Address,,1 Family housing,,2 Another Village/Neighborhood in Permanent Ad...,2 Urban Community,NaN,NaN,1998.0,2 City/Town,NaN,NaN,NaN,2 No,NaN,NaN,NaN,NaN,,NaN,,2 Non-agricultural Hukou,NaN,NaN,,NaN,,NaN,NaN,NaN,NaN,1998.0,0.0,NaN,1 Permanent Address,,NaN,,NaN,NaN,NaN,2 No,1 Yes,3 Only Hukou place has changed,NaN,1 Birthplace,,NaN,,1 Birthplace,,NaN,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,6 High school,NaN,NaN,6.0,NaN,6.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 TV University,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,1 Yes,NaN,NaN,3 Four Year College / Bachelors degree,1 Married with spouse present,1.0,NaN,1985.0,4.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,1 Never,NaN,NaN,20151118

2013

In [30]:
df_2013 = pd.read_stata("./CHARLS2013_WAVE2/psu.dta")
df_2013.city.value_counts()

Ã¯ÃûÊÐ                  9
ÄÏ²ýÊÐ                  9
±£¶¨ÊÐ                  6
ÓñÁÖÊÐ                  6
ËÄÆ½ÊÐ                  6
                       ..
ÐìÖÝÊÐ                  3
ËÕÖÝÊÐ                  3
Ç­¶«ÄÏÃç×å¶±×å×ÔÖÎÖÝ    3
¹þ¶û±õÊÐ                2
¹þ¶û±õ                  1
Name: city, Length: 126, dtype: int64